# This file is generated by Dist::Zilla::Plugin::CPANFile v6.017
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.

requires "App::TimeTracker";
required "Text::CSV_XS";

on 'build' => sub {
  requires "Module::Build" => "0.28";
};

